variables:
  NODE_VERSION: 18

.cache:
  variables:
    PATH_NODE_MODULES: src/node_modules/
    PATH_NPMRC: src/.npmrc
    PATH_SRC: src

include:
  - project: common/templates/ci-microservices
    ref: 1.7.1
    file:
      - library-ci.yaml

install:
  script:
    - cd $PATH_SRC/ && yarn install

.npm-publish-template:
  needs: [install]
  before_script:
    - cp *.md $PATH_SRC/
  script:
    - cd $PATH_SRC/
    - echo $PKG_VERSION
    - echo $PKG_TAG
    - npm --no-git-tag-version --allow-same-version version $PKG_VERSION
    - npm publish --access public --tag $PKG_TAG

