variables:
  NODE_VERSION: 18

.cache:
  variables:
    PATH_NODE_MODULES: src/node_modules/
    PATH_NPMRC: src/.npmrc
    PATH_SRC: src

include:
  - project: common/templates/ci-microservices
    ref: 1.20.0
    file:
      - library-ci.yaml
  - project: 'pi-ecommerce/cms/cms-template-ci'
    ref: '1.4.0'
    file: 'github.yaml'

stages:
  - build
  - test
  - review
  - documentation
  - deploy

install:
  script:
    - cd $PATH_SRC/ && yarn install

.npm-publish-template:
  needs: [install]
  before_script:
    - cp *.md $PATH_SRC/
    - export NPM_REGISTRY_TOKEN=$NPM_REGISTRY_PUSH_TOKEN
  script:
    - echo $NPM_REGISTRY_TOKEN
    - cd $PATH_SRC/
    - echo $PKG_VERSION
    - echo $PKG_TAG
    - npm --no-git-tag-version --allow-same-version version $PKG_VERSION
    - npm publish --access public --tag $PKG_TAG

trigger-github-workflow:
  stage: documentation
  needs:
    - release-note-jira
