variables:
  NODE_VERSION: 18

include:
  - project: common/templates/ci-microservices
    ref: 1.7.1
    file:
      - microservice_node_ci.yaml

.npm-publish-template:
  stage: deploy
  image: node:${NODE_VERSION}-slim
  extends: .cache
  when: manual
  cache:
    paths:
      - $PATH_NPMRC
  script:
    - cd $PATH_SRC/
    - echo $PKG_VERSION
    - echo $PKG_TAG
    - yarn --no-git-tag-version --allow-same-version version --new-version $PKG_VERSION
    - yarn publish --tag $PKG_TAG
  tags:
    - small


npm-publish-tag:
  extends: .npm-publish-template
  only:
    refs:
      - tags
  variables:
    PKG_VERSION: $CI_COMMIT_TAG
    PKG_TAG: "latest"

