'use strict';

module.exports = {
    SHIP_TO_CARDHOLDER_BILLING_ADDRESS: 1,
    SHIP_TO_VERIFIED_ADDRESS: 2,
    SHIP_TO_DIFFERENT_ADDRESS: 3,
    SHIP_TO_STORE: 4,
    DIGITAL_GOODS: 5,
    DIGITAL_TRAVEL_EVENT_TICKETS: 6,
    OTHER: 7
};
